version: '3.8'

services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony
    working_dir: /app
    environment:
      DATABASE_URL: "mysql://user:password@mysql:3306/db_name?serverVersion=8&charset=utf8mb4"
      MESSENGER_TRANSPORT_DSN: "doctrine://default?auto_setup=0"
    command: [ "./docker-entrypoint.sh" ]
    ports:
      - '8015:8000'
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  messenger-consumer:
    build: .
    command: php bin/console messenger:consume async --no-interaction
    depends_on:
      - symfony
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "mysql://user:password@mysql:3306/db_name?serverVersion=8&charset=utf8mb4"
      MESSENGER_TRANSPORT_DSN: "doctrine://default?auto_setup=0"

volumes:
  mysql_data:
