<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWiQmsvZ\App_Infrastructure_Symfony_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWiQmsvZ/App_Infrastructure_Symfony_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWiQmsvZ.legacy');

    return;
}

if (!\class_exists(App_Infrastructure_Symfony_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWiQmsvZ\App_Infrastructure_Symfony_KernelDevDebugContainer::class, App_Infrastructure_Symfony_KernelDevDebugContainer::class, false);
}

return new \ContainerWiQmsvZ\App_Infrastructure_Symfony_KernelDevDebugContainer([
    'container.build_hash' => 'WiQmsvZ',
    'container.build_id' => '5a2565a2',
    'container.build_time' => 1730826294,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWiQmsvZ');
