<?php

namespace ContainerKDklLlC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApp_ParseProduct_ControllerService extends App_Infrastructure_Symfony_KernelDevDebugContainer
{
    /**
     * Gets the public 'app.parse_product.controller' shared service.
     *
     * @return \App\Infrastructure\Symfony\Controller\ParseProductsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/src/Infrastructure/Symfony/Controller/ParseProductsController.php';
        include_once \dirname(__DIR__, 3).'/src/Product/Factory/ProductFactory.php';

        return $container->services['app.parse_product.controller'] = new \App\Infrastructure\Symfony\Controller\ParseProductsController(($container->privates['app.product.fetcher'] ?? $container->load('getApp_Product_FetcherService')), ($container->privates['app.product.factory'] ??= new \App\Product\Factory\ProductFactory()));
    }
}
