<?php

namespace ContainerKDklLlC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApp_Product_FetcherService extends App_Infrastructure_Symfony_KernelDevDebugContainer
{
    /**
     * Gets the private 'app.product.fetcher' shared service.
     *
     * @return \App\Infrastructure\Symfony\Parser\ProductFetcher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/src/Infrastructure/Symfony/Parser/ProductFetcher.php';
        include_once \dirname(__DIR__, 3).'/src/Product/Factory/ProductFactory.php';

        return $container->privates['app.product.fetcher'] = new \App\Infrastructure\Symfony\Parser\ProductFetcher(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['app.product.factory'] ??= new \App\Product\Factory\ProductFactory()));
    }
}
