parameters:
    service_name: 'test-pars-site'
    mysql.dsn: '%env(resolve:DATABASE_URL)%'
    csv_file_path: '%kernel.project_dir%/App/Product/products.csv'

services:
  app.product.storage: '@app.product.storage.mysql'

  app.product.factory:
    class: App\Product\Factory\ProductFactory

  app.parser.html_fetcher:
    class: App\Parser\HtmlFetcher
    arguments:
      - '@http_client'

  app.parser.crawler.book:
    class: App\Infrastructure\Symfony\Parser\CrawlerBookParser
    arguments:
      - '@app.parser.html_fetcher'
      - '@app.product.factory'

  app.product.storage.mysql:
    class: App\Infrastructure\Storage\Mysql\ProductMysqlStorage
    arguments:
      - '@doctrine.dbal.mysql_connection'
      - '@app.product.factory'

  app.get_products.controller:
    public: true
    class: App\Infrastructure\Symfony\Controller\GetProductsController
    arguments:
      - '@app.product.storage'

  app.parse_product.command:
    public: true
    class: App\Infrastructure\Symfony\Command\ParseProductsCommand
    arguments:
      - '@app.parser.crawler.book'
      - '@app.product.storage'
      - '@messenger.bus.default'
    tags:
      - { name: console.command }

  app.parse_product.message_handler:
    public: true
    class: App\Infrastructure\Queue\Handler\WriteToCsvMessageHandler
    arguments:
      - '%csv_file_path%'
    tags:
      - { name: messenger.message_handler }