<?php

namespace ContainerWiQmsvZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_ARy6nX9Service extends App_Infrastructure_Symfony_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.ARy6nX9' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 3).'/src/Product/Queue/Handler/WriteToCsvMessageHandler.php';

        return $container->privates['.messenger.handler_descriptor.ARy6nX9'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['app.parse_product.message_handler'] ??= new \App\Product\Queue\Handler\WriteToCsvMessageHandler()), []);
    }
}
