<?php

namespace ContainerWiQmsvZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApp_ParseProduct_MessageHandlerService extends App_Infrastructure_Symfony_KernelDevDebugContainer
{
    /**
     * Gets the public 'app.parse_product.message_handler' shared service.
     *
     * @return \App\Product\Queue\Handler\WriteToCsvMessageHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/src/Product/Queue/Handler/WriteToCsvMessageHandler.php';

        return $container->services['app.parse_product.message_handler'] = new \App\Product\Queue\Handler\WriteToCsvMessageHandler();
    }
}
